version: "3"

services:
  app:
    container_name: fake-data-generator
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
        - ./:/app
    command: ["./entrypoint.sh"]
    env_file:
      - .env
    depends_on:
      - db


  db:
    image: postgres:13.4-alpine
    container_name: data_db
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"


  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A data_faker worker -l INFO"
    depends_on:
      - redis
      - db
    restart: on-failure
    env_file:
      - .env
