# Generated by Django 5.0.1 on 2024-01-31 09:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "column_separator",
                    models.CharField(
                        choices=[
                            (",", "Comma(,)"),
                            (";", "Semicolon(;)"),
                            ("\t", "Tab(\t)"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "string_character",
                    models.CharField(
                        choices=[('"', 'Double Quotes(")'), ('"', "Single Quotes(')")],
                        max_length=1,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("Integer", "Integer"),
                            ("Full name", "Full name"),
                            ("Job", "Job"),
                            ("Phone number", "Phone number"),
                            ("Company", "Company"),
                            ("Text", "Text"),
                            ("Date", "Date"),
                            ("Address", "Address"),
                        ],
                        max_length=64,
                    ),
                ),
                ("min_value", models.IntegerField(blank=True, null=True)),
                ("max_value", models.IntegerField(blank=True, null=True)),
                (
                    "order",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="schemas.schema",
                    ),
                ),
            ],
            options={
                "unique_together": {("schema", "order")},
            },
        ),
    ]
