# Generated by Django 5.0.1 on 2024-02-01 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schemas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schema",
            name="number_of_rows",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
            preserve_default=False,
        ),
    ]
